image: golang:1.10

stages:
  - test

before_script:
  - cp -r /go/src/_/builds/jadr2ddude/xgraph /go/src/gitlab.com/jadr2ddude/xgraph
  - go get -v gitlab.com/jadr2ddude/xgraph/...

go_test:
  stage: test
  script:
    - go test gitlab.com/jadr2ddude/xgraph
